### PR TITLE
[MF-260] Dummy Data Inputter

### PR DESCRIPTION
**Pull request by nickjhill14**
Dummy Data Inputter Demo

- Overview: Allows the input of dummy data to speed up demos and exploratory tests.
- [JIRA Ticket](https://issues.openmrs.org/browse/MF-260)

### CODE REVIEW

**Review by FlorianRappl — APPROVED** [review]
I love this, but (even though I approve it) I miss how it is hidden or made visible towards the end-user. For development purposes this is great, but as an end-user feature I think "hm?".

Maybe making it configurable (turned off by default, or turned on if a certain localStorage key is found) would have been superb.

**Comment by nickjhill14** [comment]
Thanks for the feedback Florian, that idea sounds awesome. Maybe we could turn it on if the `devTools localStorage` key is found?

**Comment by FlorianRappl** [comment]
Sounds good to me! @nickjhill14

**Review by FlorianRappl — APPROVED** [review]

**Comment by nickjhill14** [comment]
Dummy Data Inputter Dev Tools Integration

@FlorianRappl what are your thoughts on something like this?

**Pull request merged**
