### PR TITLE
New App Shell Tooling

### PR DESCRIPTION
**Pull request by FlorianRappl**
- Consolidated the package.json
- Introduced the `openmrs` tooling
- Updated dependencies

### CODE REVIEW

**Review by denniskigen — APPROVED** [review]
🚀 Cool work @FlorianRappl! LGTM. Any thoughts on this @nickjhill14?

**Comment by nickjhill14** [comment]
> 🚀 Cool work @FlorianRappl! LGTM. Any thoughts on this @nickjhill14?

This looks cool! Is there any documentation on the Wiki about the new App Tooling? I've been a bit out of the loop recently.

**Comment by FlorianRappl** [comment]
@nickjhill14 https://github.com/openmrs/openmrs-esm-core/tree/master/packages/openmrs hope that helps!

**Comment by nickjhill14** [comment]
> @nickjhill14 https://github.com/openmrs/openmrs-esm-core/tree/master/packages/openmrs hope that helps!

Thanks! Shall we merge it in?

**Pull request merged**
