### PR TITLE
Replaced the deprecated useCurrentPatient() with the new useCurrentPatient(patientUuid) and modified the component in the tests.

### PR DESCRIPTION
**Pull request by vasharma05**
**What does this PR do?**

I have replaced the deprecated useCurrentPatient() with the new useCurrentPatient(patientUuid) and modified the component tests.

### CODE REVIEW

**Review by FlorianRappl — APPROVED** [review]
This is great! Thanks 🍻 

(now only the conflicts need to be resolved)

**Comment by vasharma05** [comment]
@FlorianRappl which conflicts are you talking about?

**Comment by vasharma05** [comment]
I'll clear them out @FlorianRappl !

**Comment by vasharma05** [comment]
@FlorianRappl I have cleared out all the conflicts. Please check the new changes!

**Pull request merged**
